### ISSUE TITLE
Error: Root object is not an identifier when getRootName called with object with `type: "AwaitExpression"`

### ISSUE THREAD

**Issue by eastlondoner** [alii/eslint-plugin-firebase-functions#3]
`Error: Root object is not an identifier` is encountered running this against my code. See stack trace below.

manual debugging shows that the object passed to getRootName has `type: identifier:AwaitExpression`. 

A bit of poking around makes me think that some code from the lint rule is being applied to every variable that's created (even variables created within inner function scopes). That might be overkill ? IDK

```
@rhizo/firebase-functions:lint: 
@rhizo/firebase-functions:lint: Oops! Something went wrong! :(
@rhizo/firebase-functions:lint: 
@rhizo/firebase-functions:lint: ESLint: 8.8.0
@rhizo/firebase-functions:lint: 
@rhizo/firebase-functions:lint: Error: Root object is not an identifier
@rhizo/firebase-functions:lint: Occurred while linting /Users/andrew/rhizo-repos/spikes/firebase/functions/src/index.ts:169
@rhizo/firebase-functions:lint: Rule: "firebase-functions/safe-function-exports"
@rhizo/firebase-functions:lint:     at getRootName (/Users/andrew/rhizo-repos/spikes/node_modules/eslint-plugin-firebase-functions/dist/index.js:12:9)
@rhizo/firebase-functions:lint:     at getRootName (/Users/andrew/rhizo-repos/spikes/node_modules/eslint-plugin-firebase-functions/dist/index.js:4:12)
@rhizo/firebase-functions:lint:     at /Users/andrew/rhizo-repos/spikes/node_modules/eslint-plugin-firebase-functions/dist/index.js:39:30
@rhizo/firebase-functions:lint:     at Array.every (<anonymous>)
@rhizo/firebase-functions:lint:     at VariableDeclaration (/Users/andrew/rhizo-repos/spikes/node_modules/eslint-plugin-firebase-functions/dist/index.js:37:79)
@rhizo/firebase-functions:lint:     at /Users/andrew/rhizo-repos/spikes/node_modules/eslint/lib/linter/timing.js:142:13
@rhizo/firebase-functions:lint:     at ruleErrorHandler (/Users/andrew/rhizo-repos/spikes/node_modules/eslint/lib/linter/linter.js:1107:28)
@rhizo/firebase-functions:lint:     at /Users/andrew/rhizo-repos/spikes/node_modules/eslint/lib/linter/safe-emitter.js:45:58
@rhizo/firebase-functions:lint:     at Array.forEach (<anonymous>)
@rhizo/firebase-functions:lint:     at Object.emit (/Users/andrew/rhizo-repos/spikes/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
```

**Comment by alii** [comment]
Fixed in fb37e601cb169032bab1107e8e38261e80e7dfef
